#server:
#  port: 11000

spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.56.20:3306/yjlmall-pms
#    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
#      discovery:
#        server-addr: 192.168.56.20:8848
      config:
        group: dev
        server-addr: 192.168.56.20:8848
        namespace: 4d8745e0-6222-48d8-be6d-a7f79eaaa8b2

  config:
    import:
#      - optional:nacos:yjlmall-product.properties # 监听 PROVIDER_GROUP :provider-config-dev.yml
#      - optional:nacos:yjlmall-product.properties?group=dev  # 覆盖默认 group，监听 group_01:provider-config-dev.yml
      - optional:nacos:datasource.yml?group=dev&refreshEnabled=true
      - optional:nacos:mybatis.yml?group=dev&refreshEnabled=true
      - optional:nacos:other.yml?group=dev&refreshEnabled=true
      #- optional:nacos:provider-server-dev.yml?group=group_02&refreshEnabled=false # 不开启动态刷新
      - nacos:yjlmall-product.yml
#  application:
#    name: yjlmall-product


#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto

